server:
  maxThreads: 8
  maxQueuedRequests: 100000
  applicationConnectors:
    - type: http
      port: 8088
      acceptQueueSize: 100000
  adminConnectors:
    - type: http
      port: 8089
      acceptQueueSize: 100000
  requestLog:
    appenders: []

client:
  maxThreads: 4
